name: Update blog posts

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    # - name: Install Composer dependencies
    #   run: composer install
    - name: Insert blog posts
      run: php time_changer.php
    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updated time
